# Generated by Django 5.0.3 on 2024-03-14 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='адрес')),
                ('payment_method', models.CharField(choices=[('КАРТА', 'CART'), ('НАЛИЧНЫЕ', 'CASH'), ('QR', 'QR')], max_length=20)),
                ('payment_state', models.CharField(choices=[('ОПЛАЧЕНО', 'PAID'), ('НЕ ОПЛАЧЕНО', 'NOT_PAID')], max_length=20)),
                ('delivery_state', models.BooleanField(default=False, verbose_name='Статус доставки')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='BasketProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('basket_pk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_pk', to='webapp.basket', verbose_name='ID корзины')),
                ('product_pk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_pk', to='webapp.product', verbose_name='ID продукта')),
            ],
        ),
    ]
