# Generated by Django 5.0.3 on 2024-03-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_product_photo_photo_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketproduct',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
