# Generated by Django 5.0.3 on 2024-03-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_basketproduct_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketproduct',
            name='price',
        ),
        migrations.AddField(
            model_name='basketproduct',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
    ]
