# Generated by Django 5.0.3 on 2024-03-31 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_rename_basket_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
